version: '3.8' # Specify the version to ensure compatibility

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - .data:/data/db
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=admin
      - MONGODB_INITDB_ROOT_PASSWORD=password
volumes:
  data: {}

networks:
  default:
    name: mongodb_network


#  eureka-server:
#    build:
#      context: eureka-server
#      dockerfile: Dockerfile
#    image: maghrebtrip/eureka-server:latest
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    container_name: eureka-server
#    ports:
#      - "8761:8761"
#    networks:
#      - spring
#
#  tourist:
#    build:
#      context: tourist
#      dockerfile: Dockerfile
#    image: maghrebtrip/tourist:latest
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    container_name: tourist
#    ports:
#      - "8080:8080"
#    networks:
#      - spring
#      - postgres
#    depends_on:
#      - eureka-server
#      - postgres
#      -
#networks:
#  postgres:
#    driver: bridge
#  spring:
#    driver: bridge
#
#volumes:
#  postgres:
#  pgadmin:
####################################################################kafka
#version: '3.9'
#
#services:
#  mongodb:
#    image: mongo:latest
#    container_name: mongodb
#    ports:
#      - 27017:27017
#    volumes:
#      - ./data:/data/db
#      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=admin
#      - MONGO_INITDB_ROOT_PASSWORD=password
#    networks:
#      - kafka_network
#
#  zookeeper:
#    image: bitnami/zookeeper:latest
#    container_name: zookeeper
#    ports:
#      - "2181:2181"
#    environment:
#      - ALLOW_ANONYMOUS_LOGIN=yes
#    networks:
#      - kafka_network
#
#  kafka:
#    image: bitnami/kafka:latest
#    container_name: kafka
#    ports:
#      - "9092:9092"
#    environment:
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
#      - ALLOW_PLAINTEXT_LISTENER=yes
#    depends_on:
#      - zookeeper
#    networks:
#      - kafka_network
#
#volumes:
#  data: {}
#
#networks:
#  kafka_network:
#    driver: bridge